name: Deploy Hugo Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true

      - name: Build
        run: hugo

      - name: Show runner public IP
        run: curl -s https://api.ipify.org

      - name: Test SSH port
        run: |
            nc -vz -w 10 "${{ secrets.HOST }}" 22

      - name: Copy public directory to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "public/"
          target: ${{ secrets.DESTINATION }}
          strip_components: 1
